"""empty message

Revision ID: 3358dab65b2a
Revises: 
Create Date: 2019-05-06 21:07:31.158617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3358dab65b2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_status',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('label', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('is_camper', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_is_camper'), 'person', ['is_camper'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', name='unique_program_year')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.String(length=255), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=True),
    sa.Column('width_orig', sa.Integer(), nullable=False),
    sa.Column('height_orig', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status'], ['image_status.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('image_face',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('bottom', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['face.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'face_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_face')
    op.drop_table('image')
    op.drop_table('face')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('program')
    op.drop_index(op.f('ix_person_is_camper'), table_name='person')
    op.drop_table('person')
    op.drop_table('image_status')
    # ### end Alembic commands ###
